// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvxaworlrsycpmjqyhni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2eGF3b3JscnN5Y3BtanF5aG5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTM3MjEsImV4cCI6MjA2OTM2OTcyMX0.aeLOq62JnOVI9eyJQe5gHSw8e4jLvbQ8NW-Kx-E9Np8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});