// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wptjlepykhhtutqvwfbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwdGpsZXB5a2hodHV0cXZ3ZmJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTA2NTgsImV4cCI6MjA3MTk2NjY1OH0.8KOEMIJBsf_bizizu0lU1u4v5BZA5fSG-AcAMYqCxnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});